blank_issues_enabled: false
contact_links:
  - name: Questions | 提问
    url: https://github.com/KuekHaoYang/KResearch/discussions/new?category=q-a
    about: If you have questions about the project, please ask here. | 如果你有关于项目的问题，请在这里提问。
  - name: Security Vulnerability | 安全漏洞
    url: https://github.com/KuekHaoYang/KResearch/security/advisories/new
    about: Report security vulnerabilities. | 报告安全漏洞。